spring:
  application:
    name: PokePad
  datasource:
    url: jdbc:postgresql://localhost:5432/pokepad_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true    # shows the queries Spring makes
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    
